## Basic types in Tensorflow

1. Constant: A Constant holds a value that cannot change. 
```
tf.constant([1, 3, 4]) or tf.constant(1) or tf.constant("I am a string")
```

2. Placeholders: These are values that are unassigned and will be assigned when the Session is started. The actual value will be needed to be fed in. Placeholders need to be initialised with an expected datatype argument, and optionally the shape. 
```
tf.placeholder(dtype=tf.float32, shape=(3, 3))
```

3. Variables: These are the values that will change. For instance, you are training a Neural Network and the weights values need to change at every iterations. These weights will be of Variable type since they keep changing. Variables need to be initialised with some value and `tf.global_variables_initializer()` should be called before using it. 
```
tf.Variable(value=10)
```

## Adding two numbers

In [5]:
# imports tensorflow
import tensorflow as tf

In [4]:
a = tf.constant(10)
b = tf.constant(20)

# operations are performed only inside a 
# session
with tf.Session() as sess:
    result = sess.run(a + b)

print("Result: {}".format(result))

Result: 30


## Working with Matrices
Matrices in Tensorflow are 2D Tensors

In [19]:
mat_a = tf.ones((4, 4))
mat_b = tf.random_normal((4, 4), mean=0, stddev=1)

print(mat_a)
print(mat_b)

with tf.Session() as sess:
    # .eval() works only inside a 
    # session. Alternatively, you can
    # also call sess.run(x) which is
    # the same thing as x.eval()
    print("Matrix one: ")
    print(mat_a.eval())
    print("Matrix two")
    print(mat_b.eval())
    print("Result (NumPy array)")
    result = sess.run(mat_a + mat_b)
    print(result)

Tensor("ones_9:0", shape=(4, 4), dtype=float32)
Tensor("random_normal_9:0", shape=(4, 4), dtype=float32)
Matrix one: 
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
Matrix two
[[ 0.15291069 -0.4500092   0.25141689  1.44968617]
 [ 1.15152729  0.23676419  0.27802321  0.18159263]
 [-1.21611249  0.41470814 -1.30151033 -0.30947879]
 [-1.10813129 -0.36050779  0.3582184   0.01854444]]
Result (NumPy array)
[[ 0.75743616  1.77799678 -0.15720248  1.48538554]
 [ 1.56402528  1.83809948  1.33680892  0.88191712]
 [-0.39555836  0.83546102  0.39450622  1.33495688]
 [ 2.83761406  1.10839438  1.65748334  0.72506559]]


## Matrix mulitplication

In [28]:
mat_a = tf.ones((4, 4), dtype=tf.int32)
mat_b = tf.fill((4, 4), 5)

with tf.Session() as sess:
    result = tf.matmul(mat_a, mat_b)
    print(result.eval())

[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]


## Variables

In [39]:
var = tf.Variable(10)
# you need to run init first to initialize
# the variables else it will throw error
init = tf.global_variables_initializer()

In [38]:
with tf.Session() as sess:
    sess.run(init)
    print(var.eval())

10


## Placeholder


In [42]:
ph_a = tf.placeholder(dtype=tf.float32)
ph_b = tf.placeholder(dtype=tf.float32)
add_op = tf.add(ph_a, ph_b)

with tf.Session() as sess:
    # feed dictionary will provide the values to 
    # be fed in for placeholders
    result = sess.run(add_op, feed_dict={ph_a: 100, ph_b: 200})
    print(result)

300.0
