In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [3]:
num_input = 2
num_hidden = 3


### Placeholders (Inputs)

In [5]:
X1 = tf.placeholder(tf.float32, shape=[None, 2])
X2 = tf.placeholder(tf.float32, shape=[None, 2])

### Variables (Weights)

In [13]:
W1 = tf.Variable(tf.random_normal(shape=[num_input, num_hidden]))
W2 = tf.Variable(tf.random_normal(shape=[num_hidden, num_hidden]))
b = tf.Variable(tf.random_normal(shape=[1, num_hidden]))

### Graph Operations


In [14]:
y0 = tf.matmul(X1, W1) + b
y1 = tf.matmul(X2, W1) + tf.matmul(y0, W2) + b
init = tf.global_variables_initializer()

In [15]:
X1_batch = np.array([[0, 1], [1, 2], [2, 3]])
X2_batch = np.array([[100, 101], [101, 102], [102, 103]])

with tf.Session() as sess:
    sess.run(init)
    y_pred0 = sess.run(y0, feed_dict={X1: X1_batch, X2: X2_batch})
    y_pred1 = sess.run(y1, feed_dict={X1: X1_batch, X2: X2_batch})
    print("Y0: {}".format(y_pred0))
    print("Y1: {}".format(y_pred1))

Y0: [[ 2.1062934   0.6099524  -0.31374425]
 [ 4.060606    2.8197536  -0.54228216]
 [ 6.0149183   5.0295553  -0.7708201 ]]
Y1: [[200.52452  218.27397  -26.710806]
 [206.42929  217.31969  -28.623743]
 [212.33406  216.3654   -30.536676]]
